
services:
  db:
    image: postgres:14-alpine
    container_name: team_project_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-teamadmin}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-supersecretpassword}
      POSTGRES_DB: ${DB_NAME:-team_app_db}
    ports:
      - "5432:5432"
    volumes:
      - postgres_team_app_data:/var/lib/postgresql/data

  backend: 
    build: . 
    container_name: team_project_backend
    restart: always
    ports:
     
    
      - "${APP_PORT:-8080}:8080" 
    environment:
      
      DB_HOST: db 
      DB_PORT: 5432
      DB_USER: ${DB_USER:-teamadmin} 
      DB_PASSWORD: ${DB_PASSWORD:-supersecretpassword}
      DB_NAME: ${DB_NAME:-team_app_db}
      APP_PORT: 8080 
    depends_on:
      - db 

volumes:
  postgres_team_app_data: